apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Role
  metadata:
    name: extension-apiserver-authentication-reader
    namespace: kube-system
  rules:
  - apiGroups:
    - ""
    resourceNames:
    - extension-apiserver-authentication
    resources:
    - configmaps
    verbs:
    - get
- kind: ClusterRole
  apiVersion: v1
  metadata:
    name: service-broker-caller
  rules:
  - nonResourceURLs:
    - /broker/sdkbroker.broker.io/*
    verbs:
    - get
    - put
    - delete
    - post
- kind: ClusterRoleBinding
  apiVersion: v1
  metadata:
    name: service-broker-caller-binding
  roleRef:
    name: service-broker-caller
  groupNames:
  - system:unauthenticated
  - system:authenticated
  - system:anonymous
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: service-broker-resource
  rules:
  - apiGroups:
    - sdkbroker.broker.k8s.io
    resources:
    - "*"
    verbs:
    - create
    - get
    - update
    - delete
    - list
- kind: ClusterRoleBinding
  apiVersion: v1
  metadata:
    name: service-broker-resource-binding
  roleRef:
    name: service-broker-resource
  groupNames:
  - system:unauthenticated
  - system:authenticated
  - system:anonymous

